version: '3.3'

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
      - 54321:5432
    restart: always
    volumes:
      - ./_pg_data:/var/lib/postgresql/data
